resource_types:
- name: staticfile
  type: docker-image
  source:
    repository: czero/staticfile-resource

resources:
- name: configuration
  type: staticfile
  source:
    files:
    - filename: config.yml
      data: |
        hello: world
    - filename: other-config.yml
      data: |
        goodbye: world

jobs:
- name: print-config
  plan:
  - get: configuration
  - task: print-config
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: ubuntu}
      inputs:
      - name: configuration
      run:
        path: cat
        args:
        - configuration/config.yml
        - configuration/other-config.yml
