resource_types:
- name: staticfile
  type: docker-image
  source:
    repository: czero/staticfile-resource

resources:
- name: staticfile-resource
  type: git
  source:
    uri: git@github.com:pivotal-cf/staticfile-resource.git
    branch: master
    private_key: ((git_private_key))

- name: staticfile-resource-image
  type: docker-image
  source:
    repository: czero/staticfile-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: base-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: base

jobs:
- name: run-tests
  plan:
  - aggregate:
    - get: staticfile-resource
      trigger: true
  - task: run-tests
    file: staticfile-resource/ci/tasks/run-tests/task.yml

- name: bump-image
  plan:
  - aggregate:
    - get: staticfile-resource
      passed: [run-tests]
      trigger: true
    - get: base-image
      trigger: true
  - task: prepare-workspace
    file: staticfile-resource/ci/tasks/prepare-workspace/task.yml
  - put: staticfile-resource-image
    params:
      build: workspace
